dist: trusty
sudo: required

language: c

compiler:
 - clang
 - gcc

before_script:
 - sudo apt-get install libldap2-dev libmysqlclient-dev libpq-dev libssl-dev
 - ./.travis-libsodium.sh
 - ./autogen.sh
 - ./configure --disable-dependency-tracking --with-everything --with-ldap --with-mysql --with-pgsql --with-tls

script:
 - make -j$(nproc) distcheck
